import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ChevronLeft, Loader2, ReceiptText, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";

const currency = (value: number | string | null | undefined) => new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP", minimumFractionDigits: 2 }).format(Number(value ?? 0));
const localDate = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Manila" }).format(new Date());
const displayDate = (value: string | null) => value ? new Date(`${value}T12:00:00`).toLocaleDateString("en-PH", { month: "long", day: "numeric", year: "numeric" }) : "—";
const moneyFields = [["landingPageInitialOrder", "LANDING PAGE INITIAL ORDER"], ["resellerDistributorPackage", "RESELLER/DISTRIBUTOR PACKAGE"], ["messaging", "MESSAGING"], ["warmLeadsOutboundCalls", "WARM LEADS/OUTBOUND CALLS"], ["advancedPayment", "ADVANCED PAYMENT"], ["hotleadsUpsellCalls", "LANDING PAGE WITH UPSELL"]] as const;
type PaymentStatus = "no_payment" | "initial_payment" | "fully_paid";
type PaymentMethod = "cash" | "gcash" | "bank_transfer" | "card" | "other";
type FormState = { saleDate: string; customerName: string; categoryId: string; landingPageInitialOrder: string; resellerDistributorPackage: string; messaging: string; warmLeadsOutboundCalls: string; advancedPayment: string; hotleadsUpsellCalls: string; paymentStatus: PaymentStatus; initialPaymentAmount: string; paymentDate: string; paymentMethod: PaymentMethod | "" };
const initialForm = (): FormState => ({ saleDate: localDate(), customerName: "", categoryId: "", landingPageInitialOrder: "0.00", resellerDistributorPackage: "0.00", messaging: "0.00", warmLeadsOutboundCalls: "0.00", advancedPayment: "0.00", hotleadsUpsellCalls: "0.00", paymentStatus: "no_payment", initialPaymentAmount: "0.00", paymentDate: localDate(), paymentMethod: "" });
const parseAmount = (value: string) => Number(value.replace(/,/g, "")) || 0;
const paymentLabel = (value: PaymentStatus) => value === "initial_payment" ? "Advance / initial payment" : value === "fully_paid" ? "Fully paid" : "COD";
const methodLabel = (value: string) => ({ cash: "Cash", gcash: "GCash", bank_transfer: "Bank transfer", card: "Card", other: "Other" } as Record<string, string>)[value] || "—";

export default function NewSale() {
  const { user } = useAuth(); const [form, setForm] = useState<FormState>(initialForm); const [confirmOpen, setConfirmOpen] = useState(false); const [success, setSuccess] = useState(false);
  const { data: categories, isLoading: categoriesLoading } = trpc.categories.list.useQuery(); const utils = trpc.useUtils();
  const createSale = trpc.sales.create.useMutation({ onSuccess: () => { setConfirmOpen(false); setSuccess(true); utils.sales.dashboard.invalidate(); utils.sales.mine.invalidate(); toast.success("Sale successfully recorded."); }, onError: (error) => toast.error(error.message) });
  const total = useMemo(() => [form.landingPageInitialOrder, form.resellerDistributorPackage, form.messaging, form.warmLeadsOutboundCalls, form.hotleadsUpsellCalls].reduce((sum, value) => sum + parseAmount(value), 0), [form]);
  const paymentAmount = form.paymentStatus === "fully_paid" ? total : form.paymentStatus === "initial_payment" ? parseAmount(form.initialPaymentAmount) : 0;
  const remainingBalance = Math.max(0, total - paymentAmount);
  const selectedCategory = categories?.find((category) => String(category.id) === form.categoryId);
  const update = (key: keyof FormState, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const canReview = form.customerName.trim().length > 0 && Boolean(form.categoryId) && !categoriesLoading && (form.paymentStatus === "no_payment" || (Boolean(form.paymentDate) && Boolean(form.paymentMethod) && (form.paymentStatus === "fully_paid" || paymentAmount > 0) && paymentAmount <= total));
  const review = (event: React.FormEvent) => { event.preventDefault(); if (!form.customerName.trim()) return toast.error("Customer name is required."); if (!form.categoryId) return toast.error("Choose a sales category."); if (form.paymentStatus !== "no_payment" && (!form.paymentDate || !form.paymentMethod)) return toast.error("Payment date and payment method are required."); if (paymentAmount > total) return toast.error("Initial payment cannot be greater than Total POS Sales."); if (form.paymentStatus === "initial_payment" && paymentAmount <= 0) return toast.error("Enter the initial payment amount."); setConfirmOpen(true); };
  const submit = () => createSale.mutate({ ...form, categoryId: Number(form.categoryId), initialPaymentAmount: paymentAmount.toFixed(2), paymentDate: form.paymentStatus === "no_payment" ? null : form.paymentDate, paymentMethod: form.paymentStatus === "no_payment" ? null : form.paymentMethod as PaymentMethod });
  const reset = () => { setForm(initialForm()); setSuccess(false); };
  if (success) return <div className="min-h-screen px-5 py-12 md:px-10 max-w-3xl mx-auto flex items-center"><div className="w-full rounded-[2rem] bg-white border border-[#e3ebe6] p-8 md:p-12 text-center shadow-[0_18px_50px_rgba(20,63,53,0.08)]"><div className="mx-auto h-16 w-16 rounded-full bg-[#d7eee4] flex items-center justify-center text-[#143f35]"><CheckCircle2 className="h-8 w-8" /></div><p className="mt-6 text-xs font-semibold uppercase tracking-[0.22em] text-[#ef7b55]">Recorded</p><h1 className="mt-2 text-4xl font-semibold tracking-[-0.04em] text-[#143f35]">Sale successfully recorded.</h1><p className="mt-3 text-[#6b7c73]">The entry is now part of your sales history.</p><div className="mt-8 flex flex-col sm:flex-row gap-3 justify-center"><Button onClick={reset} className="rounded-xl bg-[#143f35] hover:bg-[#0f3029] h-11 px-6">Add another sale</Button><Link href="/my-sales" className="inline-flex items-center justify-center rounded-xl border border-[#dbe6df] px-6 h-11 text-sm font-semibold text-[#143f35] hover:bg-[#f6f7f5]">View my sales</Link></div></div></div>;
  return <div className="min-h-screen px-5 py-7 md:px-10 md:py-10 max-w-5xl mx-auto"><div className="mb-8"><Link href="/" className="inline-flex items-center gap-1 text-sm font-medium text-[#6b7c73] hover:text-[#143f35]"><ChevronLeft className="h-4 w-4" /> Back to overview</Link><div className="mt-6 flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#ef7b55]">Sales encoding</p><h1 className="mt-2 text-4xl md:text-5xl font-semibold tracking-[-0.05em] text-[#143f35]">New sale</h1><p className="mt-2 text-[#6b7c73]">Capture the details while the conversation is still fresh.</p></div><div className="hidden md:flex items-center gap-2 rounded-full bg-[#e8f3ed] px-4 py-2 text-xs font-semibold text-[#527064]"><ShieldCheck className="h-4 w-4" /> Agent identity locked</div></div></div>
    <form onSubmit={review} className="space-y-5"><section className="rounded-[1.5rem] bg-white border border-[#e3ebe6] p-6 md:p-8"><SectionTitle eyebrow="Sale information" title="When and who" /><div className="grid gap-5 md:grid-cols-2"><Field label="DATE"><Input type="date" value={form.saleDate} onChange={(e) => update("saleDate", e.target.value)} className="h-12 rounded-xl bg-[#fbfcfb]" required /></Field><Field label="AGENT NAME"><div className="h-12 rounded-xl bg-[#edf5f0] px-4 flex items-center text-sm font-semibold text-[#143f35]">{user?.name || "Current agent"}<span className="ml-auto text-xs font-medium text-[#7c9186]">Auto-filled</span></div></Field></div></section>
      <section className="rounded-[1.5rem] bg-white border border-[#e3ebe6] p-6 md:p-8"><SectionTitle eyebrow="Customer information" title="Who did you speak with?" /><Field label="CUSTOMER'S NAME"><Input value={form.customerName} onChange={(e) => update("customerName", e.target.value)} placeholder="e.g. Juan Dela Cruz" className="h-12 rounded-xl bg-[#fbfcfb]" required /></Field></section>
      <section className="rounded-[1.5rem] bg-white border border-[#e3ebe6] p-6 md:p-8"><SectionTitle eyebrow="Sales breakdown" title="Break the sale down" /><div className="grid gap-5 md:grid-cols-2"><Field label="SALES CATEGORY"><select value={form.categoryId} onChange={(event) => update("categoryId", event.target.value)} className="h-12 w-full rounded-xl border border-[#dbe6df] bg-[#fbfcfb] px-4 text-sm text-[#143f35] outline-none focus:ring-2 focus:ring-[#ef7b55]/30" required><option value="">{categoriesLoading ? "Loading categories…" : "Select a category"}</option>{categories?.filter((category) => category.isActive === 1).map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></Field>{moneyFields.map(([key, label]) => <Field key={key} label={label}><AmountInput value={form[key]} onChange={(value) => update(key, value)} /></Field>)}</div><p className="mt-5 text-xs text-[#8a9d92]">Advanced payment is a sales category amount and is tracked separately from client payment collection.</p></section>
      <section className="rounded-[1.5rem] bg-white border border-[#e3ebe6] p-6 md:p-8"><SectionTitle eyebrow="Payment details" title="Did the client make an initial payment?" /><div className="grid gap-5 md:grid-cols-2"><Field label="PAYMENT STATUS"><select value={form.paymentStatus} onChange={(event) => update("paymentStatus", event.target.value)} className="h-12 w-full rounded-xl border border-[#dbe6df] bg-[#fbfcfb] px-4 text-sm text-[#143f35] outline-none focus:ring-2 focus:ring-[#ef7b55]/30"><option value="no_payment">COD</option><option value="initial_payment">Advance / initial payment</option><option value="fully_paid">Fully paid</option></select></Field>{form.paymentStatus !== "no_payment" && <Field label={form.paymentStatus === "fully_paid" ? "PAID AMOUNT" : "INITIAL PAYMENT AMOUNT"}><AmountInput value={form.paymentStatus === "fully_paid" ? total.toFixed(2) : form.initialPaymentAmount} onChange={(value) => update("initialPaymentAmount", value)} /></Field>}</div>{form.paymentStatus !== "no_payment" && <div className="mt-5 grid gap-5 md:grid-cols-2"><Field label="PAYMENT DATE"><Input type="date" value={form.paymentDate} onChange={(e) => update("paymentDate", e.target.value)} className="h-12 rounded-xl bg-[#fbfcfb]" required /></Field><Field label="PAYMENT METHOD"><select value={form.paymentMethod} onChange={(e) => update("paymentMethod", e.target.value)} className="h-12 w-full rounded-xl border border-[#dbe6df] bg-[#fbfcfb] px-4 text-sm text-[#143f35]" required><option value="">Select payment method</option><option value="cash">Cash</option><option value="gcash">GCash</option><option value="bank_transfer">Bank transfer</option><option value="card">Card</option><option value="other">Other</option></select></Field></div>}<div className="mt-5 grid gap-3 sm:grid-cols-3"><BalanceItem label="TOTAL ORDER AMOUNT" value={currency(total)} /><BalanceItem label="INITIAL PAYMENT" value={currency(paymentAmount)} /><BalanceItem label="REMAINING BALANCE" value={currency(remainingBalance)} accent /></div></section>
      <section className="rounded-[1.5rem] bg-[#143f35] p-6 md:p-8 text-white flex flex-col sm:flex-row sm:items-end sm:justify-between gap-6"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#a9d8c4]">Total</p><h2 className="mt-2 text-2xl font-semibold tracking-tight">TOTAL POS SALES</h2><p className="mt-1 text-sm text-[#b7d8cb]">Calculated from five sale amount fields.</p></div><p className="text-4xl md:text-5xl font-semibold tracking-[-0.05em] text-[#f6fbf8]">{currency(total)}</p></section><div className="flex flex-col-reverse sm:flex-row sm:justify-end gap-3"><Button type="button" variant="outline" onClick={reset} className="h-12 rounded-xl border-[#dbe6df] text-[#527064]">Clear form</Button><Button type="submit" disabled={!canReview} className="h-12 rounded-xl bg-[#ef7b55] hover:bg-[#d96845] text-white px-7"><ReceiptText className="h-4 w-4 mr-2" />Review & confirm</Button></div></form>{confirmOpen && <ConfirmModal form={form} total={total} paymentAmount={paymentAmount} remainingBalance={remainingBalance} agentName={user?.name || "Current agent"} categoryName={selectedCategory?.name || "—"} pending={createSale.isPending} onBack={() => setConfirmOpen(false)} onConfirm={submit} />}</div>;
}
function SectionTitle({ eyebrow, title }: { eyebrow: string; title: string }) { return <div className="mb-6"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#ef7b55]">{eyebrow}</p><h2 className="mt-1 text-xl font-semibold tracking-tight text-[#143f35]">{title}</h2></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><Label className="mb-2 block text-[11px] font-semibold tracking-[0.14em] text-[#6b7c73]">{label}</Label>{children}</div>; }
function AmountInput({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <div className="relative"><span className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-sm font-medium text-[#8a9d92]">₱</span><Input type="text" inputMode="decimal" value={value} onChange={(e) => onChange(e.target.value.replace(/[^0-9.,]/g, ""))} onFocus={(e) => onChange(e.target.value.replace(/,/g, ""))} onBlur={(e) => { const numeric = parseAmount(e.target.value); onChange(numeric.toLocaleString("en-PH", { minimumFractionDigits: 2, maximumFractionDigits: 2 })); }} className="h-12 rounded-xl bg-[#fbfcfb] pl-9 text-right font-medium" aria-label="Amount in Philippine pesos" /> </div>; }
function BalanceItem({ label, value, accent = false }: { label: string; value: string; accent?: boolean }) { return <div className={`rounded-xl p-4 ${accent ? "bg-[#e8f3ed]" : "bg-[#f8faf8]"}`}><p className="text-[10px] font-semibold tracking-[0.14em] text-[#7c9186]">{label}</p><p className={`mt-1 text-lg font-semibold ${accent ? "text-[#143f35]" : "text-[#527064]"}`}>{value}</p></div>; }
function ConfirmModal({ form, total, paymentAmount, remainingBalance, agentName, categoryName, pending, onBack, onConfirm }: { form: FormState; total: number; paymentAmount: number; remainingBalance: number; agentName: string; categoryName: string; pending: boolean; onBack: () => void; onConfirm: () => void }) { const rows: Array<[string, string]> = [["Date", displayDate(form.saleDate)], ["Agent", agentName], ["Customer", form.customerName], ["Sales Category", categoryName], ["Payment Status", paymentLabel(form.paymentStatus)], ["Payment Amount", currency(paymentAmount)], ["Payment Date", form.paymentStatus === "no_payment" ? "—" : displayDate(form.paymentDate)], ["Payment Method", form.paymentStatus === "no_payment" ? "—" : methodLabel(form.paymentMethod)], ["Remaining Balance", currency(remainingBalance)], ["Landing Page Initial Order", currency(parseAmount(form.landingPageInitialOrder))], ["Reseller / Distributor Package", currency(parseAmount(form.resellerDistributorPackage))], ["Messaging", currency(parseAmount(form.messaging))], ["Warm Leads / Outbound Calls", currency(parseAmount(form.warmLeadsOutboundCalls))], ["Advanced Payment", currency(parseAmount(form.advancedPayment))], ["Landing Page With Upsell", currency(parseAmount(form.hotleadsUpsellCalls))]]; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#143f35]/45 p-4 backdrop-blur-sm"><div className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-[1.5rem] bg-white shadow-2xl"><div className="border-b border-[#e3ebe6] p-6"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#ef7b55]">One last look</p><h2 className="mt-2 text-2xl font-semibold tracking-tight text-[#143f35]">Confirm sales entry</h2><p className="mt-1 text-sm text-[#6b7c73]">Review the order and payment details before saving them permanently.</p></div><div className="p-6 space-y-3">{rows.map(([label, value]) => <div key={label} className="flex items-start justify-between gap-5 text-sm"><span className="text-[#7c9186]">{label}</span><span className="text-right font-medium text-[#143f35]">{value}</span></div>)}<div className="mt-5 rounded-xl bg-[#e8f3ed] p-4 flex items-end justify-between"><span className="text-xs font-semibold uppercase tracking-[0.16em] text-[#527064]">Total POS Sales</span><span className="text-2xl font-semibold text-[#143f35]">{currency(total)}</span></div></div><div className="flex flex-col-reverse sm:flex-row justify-end gap-3 border-t border-[#e3ebe6] p-6"><Button variant="outline" onClick={onBack} disabled={pending} className="h-11 rounded-xl border-[#dbe6df]">Back / edit</Button><Button onClick={onConfirm} disabled={pending} className="h-11 rounded-xl bg-[#143f35] hover:bg-[#0f3029]">{pending ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <CheckCircle2 className="h-4 w-4 mr-2" />}Confirm & submit</Button></div></div></div>; }
